language: java

matrix:
  include:
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk10
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: oraclejdk9
    - jdk: oraclejdk8

env:
  global:
    - secure: iYyxChEf+Q2iynKaDKVD6hwbqTIS0VgPvA1quFM9ZL5W+EoQXOOqSN+dILzDAYxWieS9ozmRKOWADfk4O85cp92VL9OjKo9IoS/f6ESm6uR9dc1fa7FqcBIBfc7/LtydpXrUkCS5xgSdmgfys5ks2caEle6Tib1oxzDaVJ8o3JY=
addons:
  chrome: stable
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver    
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - ".utility/push-output-to-ghpages.sh"